name: Waka Readme

on:
    workflow_dispatch:
        schedule:
            # Runs at 04:20AM
            - cron: '0 04,20 * * *'

jobs:
    update-readme:
        name: Update this repo's README
        runs-on: ubuntu-latest
        steps:
            - uses: anmol098/waka-readme-stats@master
            with:
                WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                SHOW_OS: "False"
                SHOW_UPDATED_DATE: "True"
                SHOW_LINES_OF_CODE: "True"
                SHOW_PROFILE_VIEWS: "False"
                SHOW_PROJECTS: "False"
                SHOW_LOC_CHART: "False"
                LOCALE: "en"